### ISSUE TITLE
[FEATURE]支持自定义 OpenAI 格式的 API 和自定义模型

### ISSUE THREAD

**Issue by LucienShui** [1Panel-dev/MaxKB#9]
### MaxKB 版本

v0.9.0 (build at 2024-03-21T18:39, commit: 96a0e4bc)

### 请描述您的需求或者改进建议

现在只支持添加 Azure OpenAI 的 API，以及`基础模型`只能选 `gpt-3.5-turbo` 系列和 `gpt-4-0613`。

建议增加 OpenAI 格式的自定义模型，并且将`基础模型`改为自由输入而不是下拉框。毕竟`llama.cpp`、`vllm`等开源项目更广泛地支持的是 OpenAI 的 API 格式。

Reference: [platform.openai.com](https://platform.openai.com/docs/guides/text-generation)

**Comment by baixin513** [comment]
您好，当前 Ollama 平台的基础模型支持自定义输入。
Azure OpenAI 和千帆大模型还不支持自定义输入是因为不同模型入参可能会不一致，所以暂时还没放开自定义输入。

**Comment by beijingtl** [comment]
可以增加自定义的输入，而不是基于Ollama的输入，例如常用的Qwen/ChatGLM等系列

**Comment by LucienShui** [comment]
> 您好，我看在 0.9.1 的版本中标记此 feature request 为已完成，但是更新软件后查看网页、查看源代码，均没有看见我与 @beijingtl 希望的形式。
> 
> 我将提供一个 PR 以实现此功能。

对不起，看了代码结构和复杂度之后放弃了，坐等官方实现吧。

参考 https://github.com/geekan/MetaGPT 的实现：

```yaml
llm:
  api_type: "openai"  # or azure / ollama / open_llm etc. Check LLMType for more options
  model: "gpt-4-turbo-preview"  # or name of your self-hosted model, like gemma or qwen
  base_url: "https://api.openai.com/v1"  # or forward url / other llm url
  api_key: "YOUR_API_KEY"
```
